### PR TITLE
correction in get_vlan_list()

### PR DESCRIPTION
**Pull request by pageschrist**
Small correction to fix a bug in get_vlan_list()

### CODE REVIEW

**Review by pemberso-xilinx — COMMENTED** [review]
Hi @pageschrist .  Could you add a small note on the issue being addressed by this patch. I.e. expected behaviour that was previously failing that the patch corrects.  Thanks

**Comment by abrunnin-xilinx** [comment]
(This relates ot issue #15, but it would indeed be a good idea for the commit to have that issue# in the title)

**Comment by pageschrist** [comment]
Yes , exactly it was related to this issue. I am not very familar with the best practices. I will follow the procedure for the next time.:)
Thanks

**Comment by abrunnin-xilinx** [comment]
Sorry for the delay on actually merging this in.  I've also got a selftest that demonstrates this fix (so we won't regress), which I'll merge in soon.  (Right now it's a bit too finicky about the pre-test configuration, relying on our in-house setup a bit too much for it to be usefully published).

**Pull request merged**
